spring.datasource.url=jdbc:postgresql://ep-autumn-mud-apkvvqnm.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CoGAfkeVB93M
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
jwt.secret=shabnam_super_secret_key_123456789012345
jwt.expiration=86400000
server.port=8080